### ISSUE TITLE
Improve e2e speed by using the next possible round 

### ISSUE THREAD

**Issue by webmaster128** [noislabs/nois-contracts#262]
Nois connects to a drand network with 3s beacons. Right now when a job comes in, the  drand round with publishing time > `after` and `round % 10 == 0` is used. This means we wait between 0-30 seconds for the round to be published. This on average is plenty of waiting time and the range between best and worst case is betty big. We want to improve the UX by removing the `round % 10 == 0` condition and take use every possible round. However, this also means we cannot just submit all rounds multiple times the way we do it now as it would create 10x the load on the blockchain. The usage of those submitted round is pretty low. So it is much better to change the system in a way that waits for RequestBeacon packets and then processes all jobs in the job queue, no matter which round they then need.

## Advantages

- With a global jobs queue it becomes almost impossible to have unprocessed jobs that get forgotten. Even old jobs will easily be processed by a bot.
- Way more resource efficient (both gas for verification and storage)
- More sustainable business model since rewards are always paid in case of a purchase
- Faster 🚅

## Disadvantages

- Bot needs to connect to two contracts (gateway and drand): no big deal really but slightly more complex
- We need to figure out incentivisation

## Action plan

Here is a probably incomplete action plan to get there:

- [x] Upgrade gateway to 0.13.6 which provides a jobs query
    - [x] Testnet
    - [x] Mainnet
- [x] Let bot observe pending jobs and log them (https://github.com/noislabs/bot2/pull/13)
    - [x] Add gateway contract address to bot
    - [x] Make jobs query efficient
     - [x] Upgrade gateway to 0.13.7 which provides an efficient jobs query (#263)
         - [x] Testnet
         - [ ] Mainnet
    - [x] Read committed round from job's `source`
- [ ] Add setting to only submit beacon for queued jobs
- [x] Create beacon cache in bot
- [ ] Incentivise based on job processing
- [ ] Create basic load to incentivise bots and test the system
- [ ] drand: accept all rounds
- [ ] Let gateway commit to next round

**Comment by webmaster128** [comment]
done in #266
